site_name: "Mark Veltzer's personal site"
site_url: "https://veltzer.github.io"
theme:
  name: "material"
docs_dir: "blog"
site_dir: "docs"
plugins:
  - search:
  - blog:
      blog_dir: .
nav:
  - 'Home': 'index.md'
  - 'About Me': 'about.md'
  - 'Calendar': '/calendar_full.html'
