site_name: "Mark Veltzer's personal site"
site_url: "https://veltzer.github.io"
extra_css:
  - "custom.css"
theme:
  name: "material"
docs_dir: "blog"
site_dir: "docs"
plugins:
  - search:
  - blog:
      blog_dir: .
nav:
  - 'Home': 'index.md'
  - 'About Me': 'about.md'
  - 'My Media Consumption': '/media.html'
  - 'Calendar full': '/calendar_full.html'
  - 'Calendar google embed': '/calendar_google_embed.html'
  - 'Calendar list view': '/calendar_list_view.html'
  - 'Chess': '/chess.html'
  - 'Board': '/board.html'
