name: build
on: push

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        cache: pip
    - uses: actions/setup-node@v6
      with:
        cache: npm
    - uses: actions/cache@v5
      with:
        path: .rsconstruct
        key: rsconstruct
    - name: install rsconstruct
      run: |
        gh release download --repo veltzer/rsconstruct --pattern 'rsconstruct-linux-x86_64' --output /usr/local/bin/rsconstruct
        chmod +x /usr/local/bin/rsconstruct
        rsconstruct version
      env:
        GH_TOKEN: ${{ github.token }}
    - name: install
      run: |
        rsconstruct tools install-deps --yes
        rsconstruct tools install --yes
    - name: build
      run: rsconstruct build --verbose -j0
    - name: status
      run: rsconstruct status
    - uses: actions/upload-pages-artifact@v3
    - uses: actions/deploy-pages@v5
